### ISSUE TITLE
Plugin does not seem to work with 3.7.5

### ISSUE THREAD

**Issue by amarjeet27** [rabbitmq/rabbitmq-management-themes#6]
I downloaded the pre-compiled version from [here](https://dl.bintray.com/rabbitmq/community-plugins/3.7.x/rabbitmq_management_themes/).

The plugin is enabled.
<img width="330" alt="plugin-enabled" src="https://user-images.githubusercontent.com/22900687/44436440-02fc3680-a56a-11e8-9548-cd8d27c1eb2a.png">

But, I don't see "Themes" on the top right corner.
<img width="861" alt="rabbitmq" src="https://user-images.githubusercontent.com/22900687/44436477-3c34a680-a56a-11e8-8dad-1cdfe4d6e027.png">

Did anyone have luck in getting this plugin to work with 3.7.5?

**Comment by michaelklishin** [comment]
Thank you for your time.

Team RabbitMQ uses GitHub issues for specific actionable items engineers can work on. GitHub issues are not used for questions, investigations, root cause analysis, discussions of potential issues, etc (as defined by this team).

We get at least a dozen of questions through various venues every single day, often light on details.
At that rate GitHub issues can very quickly turn into a something impossible to navigate and make sense of even for our team. Because GitHub is a tool our team uses heavily nearly every day, the signal/noise ratio of issues is something we care about a lot.

Please post this to [rabbitmq-users](https://groups.google.com/forum/#!forum/rabbitmq-users).

Thank you.

**Comment by michaelklishin** [comment]
This is not a tier 1 plugin so it might need updating for 3.7.x but keep in mind that it was primarily developed as a joke.
